### PR TITLE
Add automatic CI versioning

### PR DESCRIPTION
**Pull request by mdgbayly**
Updates travis.yml to use frauci-update-version to bump package.json version and tag commit on each commit/pr merge to master. Use travis releases provider to create a new github release matching tag.

### CODE REVIEW

**Comment by CodeBaboon** [comment]
Presumably this is replacing [update.sh](https://github.com/Brightspace/d2l-fetch/blob/master/update.sh)? If so, likely we should delete that file as part of this.

**Comment by mdgbayly** [comment]
@CodeBaboon Yes - this is one of the repos on which we depend a lot so i figured it made sense to try and make it consistent with how we're doing this versioning in other repos now. Deleted update.sh too.

**Comment by mdgbayly** [comment]
@CodeBaboon @ryantmer Just realized I don't have write access on this repo so if you guys are OK with switching over to the frauci version solution could one of you try merging it or else add me as a collaborator. Thanks!

**Comment by CodeBaboon** [comment]
@mdgbayly I've added you as a collaborator. The more the merrier!

**Pull request merged**
